AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - Guardfile
    - 'scripts/**/*'
    - 'db/**/*'
  TargetRubyVersion: 3.0

Layout/HashAlignment:
  Enabled: false
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Enabled: false