#!/usr/bin/env ruby
require_relative '../lib/drn/mentoring'

include Drn::Mentoring

products = Stripe::Price.list.map do |price|
  product = Stripe::Product.retrieve(price.product)
  Product[
    product_id:  product.id,
    name:        product.name,
    description: product.description,
    image_url:   product.images.first,
    price_id:    price.id,
    unit_amount: price.unit_amount,
    recurring:  !price.recurring.nil?
  ]
end

pp products

App.products.store_all!(products)
