# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby / PostgreSQL

env:
  RACK_ENV: "ci"
  DATABASE_NAME: mentoring_test
  DATABASE_URL: "postgresql://localhost/mentoring_test?username=tester&password=somestrong"
  DOMAIN: "http://localhost:3000"
  STRIPE_KEY: "test"
  STRIPE_PUB_KEY: "test"
  MENTORING_SESSION_SECRET: "secret"
  MAILJET_API_KEY: 123
  MAILJET_SECRET_KEY: 1234

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create scheduler user
        run: |
          sudo -u postgres psql --command="CREATE USER tester PASSWORD 'somestrong'" --command="\du"
      - name: Create timetable database
        run: |
          sudo -u postgres createdb --owner=tester $DATABASE_NAME
          PGPASSWORD=somestrong psql --username=tester --host=localhost --list $DATABASE_NAME
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake db:migrate db:seed spec
